    # recorded with scripts/record.py -- paste into hunt.toml [route] boot
    # remember to leave a { jitter = [0, 150] } before the battle triggers
    { wait = 162 },
    { down = "A" },
    { wait = 4 },
    { up = "A" },
    { wait = 38 },
    { down = "D_RIGHT" },
    { wait = 7 },
    { up = "D_RIGHT" },
    { wait = 16 },
    { down = "D_DOWN" },
    { wait = 5 },
    { up = "D_DOWN" },
    { wait = 43 },
    { down = "A" },
    { wait = 5 },
    { up = "A" },
    { wait = 57 },
    { down = "D_RIGHT" },
    { wait = 6 },
    { up = "D_RIGHT" },
    { wait = 75 },
    { down = "A" },
    { wait = 6 },
    { up = "A" },
    { wait = 116 },
    { down = "D_RIGHT" },
    { wait = 6 },
    { up = "D_RIGHT" },
    { wait = 52 },
    { down = "A" },
    { wait = 5 },
    { up = "A" },
    { wait = 54 },
    { down = "A" },
    { wait = 6 },
    { up = "A" },
    { wait = 127 },
    { down = "A" },
    { wait = 5 },
    { up = "A" },
    { wait = 1483 },
    { down = "D_DOWN" },
    { wait = 8 },
    { up = "D_DOWN" },
    { wait = 19 },
    { down = "A" },
    { wait = 5 },
    { up = "A" },
    { wait = 211 },
    { down = "B" },
    { wait = 5 },
    { up = "B" },
    { wait = 64 },
    { down = "D_UP" },
    { wait = 7 },
    { up = "D_UP" },