    # recorded with scripts/record.py -- paste into hunt.toml [route] boot
    # remember to leave a { jitter = [0, 150] } before the battle triggers
    { wait = 56 },
    { down = "A" },
    { wait = 5 },
    { up = "A" },
    { wait = 66 },
    { down = "A" },
    { wait = 5 },
    { up = "A" },
    { wait = 57 },
    { down = "A" },
    { wait = 6 },
    { up = "A" },
    { wait = 1102 },
    { down = "A" },
    { wait = 3 },
    { up = "A" },
    { wait = 52 },
    { down = "D_RIGHT" },
    { wait = 7 },
    { up = "D_RIGHT" },
    { wait = 25 },
    { down = "D_LEFT" },
    { wait = 7 },
    { up = "D_LEFT" },
    { wait = 56 },
    { down = "A" },
    { wait = 5 },
    { up = "A" },
    { wait = 103 },
    { down = "A" },
    { wait = 3 },
    { up = "A" },
    { wait = 64 },
    { down = "A" },
    { wait = 5 },
    { up = "A" },
    { wait = 44 },
    { down = "A" },
    { wait = 5 },
    { up = "A" },
    { wait = 35 },
    { down = "A" },
    { wait = 4 },
    { up = "A" },