    # recorded with scripts/record.py -- paste into hunt.toml [route] boot
    # remember to leave a { jitter = [0, 150] } before the battle triggers
    { wait = 1296 },
    { down = "A" },
    { wait = 9 },
    { up = "A" },
    { wait = 154 },
    { down = "A" },
    { wait = 8 },
    { up = "A" },
    { wait = 142 },
    { down = "A" },
    { wait = 7 },
    { up = "A" },
    { wait = 84 },
    { down = "D_UP" },
    { wait = 7 },
    { up = "D_UP" },
    { wait = 46 },
    { down = "A" },
    { wait = 6 },
    { up = "A" },
    { wait = 141 },
    { stick_set = [0.0, -0.18] },
    { wait = 1 },
    { stick_set = [0.0, -0.29] },
    { wait = 1 },
    { stick_set = [0.0, -0.39] },
    { wait = 1 },
    { stick_set = [0.0, -0.5] },
    { wait = 1 },
    { stick_set = [-0.15, -0.59] },
    { wait = 1 },
    { stick_set = [-0.22, -0.67] },
    { wait = 2 },
    { stick_set = [-0.31, -0.76] },
    { wait = 1 },
    { stick_set = [-0.39, -0.79] },
    { wait = 3 },
    { stick_set = [-0.48, -0.87] },
    { wait = 9 },
    { stick_set = [-0.56, -0.88] },
    { wait = 33 },
    { stick_set = [-0.44, -0.82] },
    { wait = 1 },
    { stick_set = [-0.34, -0.74] },
    { wait = 1 },
    { stick_set = [-0.27, -0.62] },
    { wait = 1 },
    { stick_set = [-0.17, -0.44] },
    { stick_set = [0.0, -0.37] },
    { wait = 1 },
    { stick_set = [0.0, -0.29] },
    { wait = 1 },
    { stick_set = [0.0, 0.0] },
    { wait = 87 },
    { stick_set = [0.0, -0.17] },
    { wait = 1 },
    { stick_set = [0.0, -0.26] },
    { wait = 2 },
    { stick_set = [0.0, -0.34] },
    { wait = 5 },
    { stick_set = [-0.15, -0.42] },
    { wait = 2 },
    { stick_set = [-0.23, -0.48] },
    { wait = 2 },
    { stick_set = [-0.32, -0.55] },
    { wait = 65 },
    { stick_set = [-0.27, -0.46] },
    { wait = 3 },
    { stick_set = [-0.19, -0.42] },
    { wait = 3 },
    { stick_set = [0.0, -0.42] },
    { wait = 4 },
    { stick_set = [0.0, -0.3] },
    { wait = 1 },
    { stick_set = [0.0, -0.21] },
    { wait = 1 },
    { stick_set = [0.0, 0.0] },
    { wait = 17 },
    { stick_set = [0.0, -0.17] },
    { wait = 1 },
    { stick_set = [0.0, -0.34] },
    { wait = 1 },
    { stick_set = [0.0, -0.45] },
    { wait = 1 },
    { stick_set = [0.0, -0.54] },
    { wait = 1 },
    { stick_set = [0.0, -0.64] },
    { wait = 1 },
    { stick_set = [0.0, -0.75] },
    { wait = 2 },
    { stick_set = [0.0, -0.84] },
    { wait = 2 },
    { stick_set = [0.0, -0.92] },
    { wait = 6 },
    { stick_set = [-0.16, -1.0] },
    { wait = 11 },
    { stick_set = [-0.25, -1.0] },
    { wait = 1 },
    { stick_set = [-0.33, -1.0] },
    { wait = 59 },
    { stick_set = [-0.25, -1.0] },
    { wait = 25 },
    { stick_set = [-0.33, -1.0] },
    { wait = 46 },
    { stick_set = [-0.42, -1.0] },
    { wait = 1 },
    { stick_set = [-0.5, -0.98] },
    { wait = 1 },
    { stick_set = [-0.59, -0.88] },
    { wait = 1 },
    { stick_set = [-0.69, -0.78] },
    { wait = 1 },
    { stick_set = [-0.76, -0.7] },
    { wait = 1 },
    { stick_set = [-0.87, -0.55] },
    { wait = 1 },
    { stick_set = [-0.93, -0.47] },
    { wait = 1 },
    { stick_set = [-0.98, -0.38] },
    { wait = 1 },
    { stick_set = [-1.0, -0.29] },
    { wait = 4 },
    { stick_set = [-1.0, -0.37] },
    { wait = 1 },
    { stick_set = [-1.0, -0.46] },
    { wait = 6 },
    { stick_set = [-1.0, -0.38] },
    { wait = 1 },
    { stick_set = [-1.0, -0.26] },
    { wait = 7 },
    { stick_set = [-0.95, -0.36] },
    { wait = 1 },
    { stick_set = [-0.88, -0.46] },
    { wait = 1 },
    { stick_set = [-0.84, -0.55] },
    { wait = 1 },
    { stick_set = [-0.83, -0.65] },
    { wait = 5 },
    { stick_set = [-0.9, -0.56] },
    { wait = 1 },
    { stick_set = [-0.95, -0.47] },
    { wait = 42 },
    { stick_set = [-0.95, -0.55] },
    { wait = 1 },
    { stick_set = [-0.89, -0.65] },
    { wait = 3 },
    { stick_set = [-0.84, -0.75] },
    { wait = 1 },
    { stick_set = [-0.75, -0.81] },
    { wait = 1 },
    { stick_set = [-0.64, -0.91] },
    { wait = 15 },
    { stick_set = [-0.73, -0.86] },
    { wait = 2 },
    { stick_set = [-0.82, -0.78] },
    { wait = 2 },
    { stick_set = [-0.88, -0.7] },
    { wait = 28 },
    { stick_set = [-0.95, -0.6] },
    { wait = 6 },
    { stick_set = [-0.9, -0.51] },
    { stick_set = [-0.75, -0.43] },
    { stick_set = [-0.52, -0.3] },
    { stick_set = [0.0, 0.0] },
    { wait = 25 },
    { stick_set = [-0.18, 0.0] },
    { stick_set = [-0.41, 0.0] },
    { stick_set = [-0.52, 0.0] },
    { wait = 1 },
    { stick_set = [-0.68, 0.0] },
    { stick_set = [-0.77, 0.0] },
    { wait = 1 },
    { stick_set = [-0.94, 0.0] },
    { wait = 6 },
    { stick_set = [0.0, 0.0] },
    { wait = 22 },
    { stick_set = [-0.31, 0.22] },
    { wait = 1 },
    { stick_set = [-0.53, 0.36] },
    { stick_set = [-0.68, 0.43] },
    { stick_set = [-0.82, 0.48] },
    { stick_set = [-0.95, 0.52] },
    { wait = 2 },
    { stick_set = [-0.76, 0.33] },
    { stick_set = [0.0, 0.0] },
    { stick_set = [0.34, 0.0] },
    { stick_set = [0.0, 0.0] },