    # recorded with scripts/record.py -- paste into hunt.toml [route] boot
    # remember to leave a { jitter = [0, 150] } before the battle triggers
    { wait = 63 },
    { stick_set = [0.0, 0.24] },
    { stick_set = [0.0, 0.33] },
    { stick_set = [0.0, 0.47] },
    { stick_set = [0.0, 0.77] },
    { stick_set = [0.0, 0.91] },
    { stick_set = [0.0, 1.0] },
    { stick_set = [-0.18, 1.0] },
    { wait = 59 },
    { stick_set = [0.0, 0.91] },
    { stick_set = [0.0, 0.83] },
    { stick_set = [0.0, 0.61] },
    { stick_set = [0.0, 0.0] },
    { wait = 15 },
    { stick_set = [-0.16, -0.18] },
    { wait = 1 },
    { stick_set = [-0.2, -0.29] },
    { wait = 1 },
    { stick_set = [-0.22, -0.41] },
    { wait = 1 },
    { stick_set = [-0.23, -0.5] },
    { wait = 1 },
    { stick_set = [-0.27, -0.61] },
    { wait = 1 },
    { stick_set = [-0.32, -0.73] },
    { wait = 1 },
    { stick_set = [-0.36, -0.82] },
    { wait = 1 },
    { stick_set = [-0.44, -0.92] },
    { wait = 1 },
    { stick_set = [-0.52, -0.98] },
    { wait = 12 },
    { stick_set = [-0.61, -0.95] },
    { wait = 2 },
    { stick_set = [-0.7, -0.88] },
    { wait = 2 },
    { stick_set = [-0.78, -0.81] },
    { wait = 38 },
    { stick_set = [-0.79, -0.73] },
    { wait = 1 },
    { stick_set = [-0.74, -0.61] },
    { wait = 1 },
    { stick_set = [-0.69, -0.48] },
    { wait = 1 },
    { stick_set = [-0.64, -0.35] },
    { wait = 1 },
    { stick_set = [-0.55, -0.19] },
    { stick_set = [-0.49, 0.0] },
    { wait = 1 },
    { stick_set = [0.0, 0.0] },
    { wait = 66 },
    { stick_set = [0.0, -0.16] },
    { wait = 1 },
    { stick_set = [0.0, -0.25] },
    { wait = 1 },
    { stick_set = [0.0, -0.33] },
    { wait = 2 },
    { stick_set = [0.0, -0.44] },
    { wait = 2 },
    { stick_set = [0.0, -0.52] },
    { wait = 4 },
    { stick_set = [0.0, -0.61] },
    { wait = 34 },
    { stick_set = [-0.17, -0.62] },
    { wait = 10 },
    { stick_set = [-0.27, -0.61] },
    { wait = 1 },
    { stick_set = [-0.38, -0.61] },
    { wait = 3 },
    { stick_set = [-0.46, -0.61] },
    { wait = 2 },
    { stick_set = [-0.55, -0.61] },
    { wait = 4 },
    { stick_set = [-0.64, -0.61] },
    { wait = 13 },
    { stick_set = [-0.55, -0.64] },
    { wait = 1 },
    { stick_set = [-0.46, -0.69] },
    { wait = 3 },
    { stick_set = [-0.55, -0.73] },
    { wait = 1 },
    { stick_set = [-0.67, -0.73] },
    { wait = 1 },
    { stick_set = [-0.76, -0.7] },
    { wait = 11 },
    { stick_set = [-0.85, -0.68] },
    { wait = 2 },
    { stick_set = [-0.71, -0.79] },
    { wait = 1 },
    { stick_set = [-0.51, -0.89] },
    { stick_set = [-0.43, -0.93] },
    { wait = 1 },
    { stick_set = [-0.34, -0.99] },
    { wait = 7 },
    { stick_set = [-0.26, -1.0] },
    { wait = 1 },
    { stick_set = [-0.18, -1.0] },
    { wait = 4 },
    { stick_set = [0.0, -1.0] },
    { wait = 8 },
    { stick_set = [-0.15, -1.0] },
    { wait = 1 },
    { stick_set = [-0.24, -1.0] },
    { wait = 56 },
    { stick_set = [-0.32, -1.0] },
    { wait = 2 },
    { stick_set = [-0.4, -1.0] },
    { wait = 14 },
    { stick_set = [-0.52, -1.0] },
    { wait = 26 },
    { stick_set = [-0.44, -1.0] },
    { wait = 4 },
    { stick_set = [-0.36, -1.0] },
    { wait = 9 },
    { stick_set = [-0.44, -1.0] },
    { wait = 1 },
    { stick_set = [-0.53, -1.0] },
    { wait = 1 },
    { stick_set = [-0.62, -0.94] },
    { wait = 15 },
    { stick_set = [-0.72, -0.86] },
    { wait = 2 },
    { stick_set = [-0.8, -0.8] },
    { wait = 9 },
    { stick_set = [-0.88, -0.71] },
    { wait = 2 },
    { stick_set = [-0.94, -0.62] },
    { wait = 14 },
    { stick_set = [-0.99, -0.51] },
    { wait = 6 },
    { stick_set = [-1.0, -0.42] },
    { wait = 5 },
    { stick_set = [-1.0, -0.33] },
    { wait = 1 },
    { stick_set = [-1.0, -0.24] },
    { wait = 1 },
    { stick_set = [-1.0, 0.0] },
    { wait = 9 },
    { stick_set = [-1.0, -0.15] },
    { wait = 1 },
    { stick_set = [-1.0, -0.23] },
    { wait = 2 },
    { stick_set = [-1.0, -0.33] },
    { wait = 4 },
    { stick_set = [-1.0, -0.43] },
    { wait = 1 },
    { stick_set = [-1.0, -0.53] },
    { wait = 2 },
    { stick_set = [-0.94, -0.63] },
    { wait = 4 },
    { stick_set = [-0.87, -0.72] },
    { wait = 1 },
    { stick_set = [-0.78, -0.81] },
    { wait = 1 },
    { stick_set = [-0.69, -0.87] },
    { wait = 1 },
    { stick_set = [-0.58, -0.95] },
    { wait = 2 },
    { stick_set = [-0.47, -0.95] },
    { wait = 2 },
    { stick_set = [-0.38, -0.95] },
    { wait = 2 },
    { stick_set = [-0.29, -0.95] },
    { wait = 3 },
    { stick_set = [-0.34, -0.84] },
    { wait = 1 },
    { stick_set = [-0.44, -0.69] },
    { wait = 2 },
    { stick_set = [-0.54, -0.61] },
    { wait = 1 },
    { stick_set = [-0.63, -0.58] },
    { wait = 1 },
    { stick_set = [-0.73, -0.52] },
    { wait = 1 },
    { stick_set = [-0.83, -0.49] },
    { wait = 1 },
    { stick_set = [-0.93, -0.48] },
    { wait = 6 },
    { stick_set = [-1.0, -0.39] },
    { wait = 2 },
    { stick_set = [-0.96, -0.31] },
    { wait = 1 },
    { stick_set = [-0.87, -0.3] },
    { wait = 10 },
    { stick_set = [-0.81, -0.38] },
    { wait = 10 },
    { stick_set = [-0.8, -0.48] },
    { wait = 1 },
    { stick_set = [-0.71, -0.56] },
    { stick_set = [-0.62, -0.62] },
    { wait = 1 },
    { stick_set = [-0.48, -0.69] },
    { wait = 1 },
    { stick_set = [-0.38, -0.73] },
    { wait = 1 },
    { stick_set = [-0.28, -0.77] },
    { wait = 7 },
    { stick_set = [-0.37, -0.73] },
    { stick_set = [-0.45, -0.68] },
    { wait = 1 },
    { stick_set = [-0.54, -0.62] },
    { wait = 7 },
    { stick_set = [-0.63, -0.57] },
    { wait = 1 },
    { stick_set = [-0.66, -0.48] },
    { wait = 1 },
    { stick_set = [-0.7, -0.37] },
    { wait = 4 },
    { stick_set = [-0.72, -0.29] },
    { wait = 2 },
    { stick_set = [-0.78, -0.19] },
    { wait = 2 },
    { stick_set = [-0.79, 0.0] },
    { wait = 7 },
    { stick_set = [-0.7, 0.0] },
    { wait = 1 },
    { stick_set = [-0.61, 0.0] },
    { wait = 1 },
    { stick_set = [-0.47, 0.0] },
    { stick_set = [-0.36, 0.0] },
    { stick_set = [0.0, 0.0] },